### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by noticz** [milowg/GMinder#23]
Been using GMinder for over a year, if GMinder is running more then a week without a computer restart it uses tons of memory. Each day it adds about 50-60 megs more of memory.

![2016-05-31_091703](https://cloud.githubusercontent.com/assets/11874318/15679821/7dc83812-2710-11e6-94a2-c1aa637358f0.jpg)

**Comment by noticz** [comment]
Any update or thoughts on this? I just got back from vacation for a week and my computer was running like a turtle...Did a check and GMinder was using over 1 MB of memory.

**Comment by milowg** [comment]
I haven't had a chance to look at this, but I definitely have not seen this happen to such an extent from my usage of GMinder. Maybe your settings are different? Can you post a screenshot of your options screen here? Also, how many typical events do you have and how many are set to remind you?

**Comment by TekBear** [comment]
Although @noticz  opended issue I am looking at it too. Here is my information.

My setup I follow a lot of public calendars about broadcast show times. 3-4 shows per day per calendar approx. for about 12 calendars. 
A search of calendars.xml for "?eid" after a "clear events" and "refresh events" got 492 hits
A snapshot from an old backup of calendars.xml had 4575 hits (many may have been past events not yet "dismissed" )

![gminder_settings_issue23-1](https://cloud.githubusercontent.com/assets/1400910/22455120/73978db8-e7c5-11e6-9c06-fb7fdaa12354.jpg)

![gminder_settings_issue23-2](https://cloud.githubusercontent.com/assets/1400910/22455124/7622c3cc-e7c5-11e6-9992-973d07d9924f.jpg)

**Comment by milowg** [comment]
I believe I may have found the problem causing this memory leak. Please try this version and let me know if it works better for you:

http://milow.net/dl/gminder/GMinder-MemoryFix.zip

I've also fixed the size of the number picker boxes on the Options page.

**Comment by TekBear** [comment]
Thanks for the input box fix ;-).  I will start testing Today and run it for a few days and check the memory footprint.  I will post when I finish testing.

**Comment by TekBear** [comment]
been running new version and virtual memory use ok.  I am  not seeing it grow significantly.
Old version
![old gminder after 14hrs 433mib](https://cloud.githubusercontent.com/assets/5044866/23052534/05e61f00-f50d-11e6-813f-46f76fd22291.jpg)
New Version
![new gminder aft 13hrs 329mib](https://cloud.githubusercontent.com/assets/5044866/23052546/1e826ed8-f50d-11e6-8806-de7343f88b27.jpg)

One small issue when I opened new version first time as main window was being built the voice announcement "event .... started 5 mins ago" triggered this interrupted and stopped the windows display completing so half the window is white space instead of future event list - see image below. Not a big deal just close and open window again.
![new gminder at start](https://cloud.githubusercontent.com/assets/5044866/23052583/6a4e6b00-f50d-11e6-9019-ce07b8dc16e8.jpg)

**Comment by milowg** [comment]
I've put v1.4.0.7 on the downloads page to fix this issue. @TekBear I could not reproduce your issue with the drawing stopping on an audio alert, but I did find a potential spot to fix and put it in there. Let me know if it still happens.

**Comment by TekBear** [comment]
@milowg thanks for looking, I know it is extremely rare to time the audio alert event to happen in middle of drawing screen - perhaps the faster the platform the greater the difficulty to trigger the behaviour.  Sure, if I come across it again I will try and get more info about it.
