### ISSUE TITLE
Gminder has not yet been verified by Google in order to use Google Sign in

### ISSUE THREAD

**Issue by TekBear** [milowg/GMinder#35]
I installed GMinder-1.4.0.8.msi and then when doing Google login in (chrome or firefox) browser I am getting the following message when I select my account:
"Sign in with Google temporarily disabled for this app.

This app has not yet been verified by Google in order to use Google Sign in."

This is a first time install of gminder on this laptop. I am unable to access google calendar data. Any ideas what I should do? 

I have used gminder on another PC and it WAS ok. I just checked that PC and has same problem. I updated that to latest Gminder but it had the same issue. I estimate gminder access must have failed months ago but I have not been using that PC for many months so did not notice it.

My google account had an app password for "GMinder win32" listed in myaccount.google.com - but setup date was 2014 / last used date was 2015. I tried deleting entry but I still get same error message on both PCs. I assume app passwords were used with GMinder circa 2014 and we're  phased out.

Under google account security web page there are these settings:
- `2-Step Verification` (current on)
- `Less secure app access` (currently off)
- `Apps with access to your account; heading Signing in with Google; Google Account sign-in prompts (currently off)`

I tested changing these settings but made no difference.Are any of these setting going to interfere with accessing data via gminder app?

ErrorLog.txt contains:
`15-08-2020 12:00:57 - Unknown Error: A task may only be disposed if it is in a completion state (RanToCompletion, Faulted or Canceled).
                      A task may only be disposed if it is in a completion state (RanToCompletion, Faulted or Cancelled).`
is repeated for each failed login attempt,

Is the authorising issue similar to this - https://github.com/insanum/gcalcli/issues/497 ?

I am testing on two vintage PCs. Is gminder still  working win7 and win 10?

Is it just me or are other people seeing this problem?

**Comment by milowg** [comment]
This may be due to the Google OAuth verification process not being complete. I had started this a while back and got a message back that says 

> Based on the type of request you’ve submitted you can skip the verification process if your app does not need to display an icon. If you decide to skip the verification process, it won’t impact the existing functionality of your app, as long as the scopes used by your project don’t change.

I just replied and asked if the verification process needs to be completed in order for your error to be solved. We'll see what Google says.

**Comment by TekBear** [comment]
Thanks @milowg. Have your tried a fresh install on a dummy google account to see if it still works - just curious.

**Comment by milowg** [comment]
I am told by Google that I have to provide some extra information to complete this process. It includes a privacy policy and a video showing the login process and app functionality.

In the past few years I've stopped using GMinder since I've switched to using MacOS. I will find some time to set up a Windows machine for this video, but it may take a little while. I'll post here when I can finish this all up.

In case you're interested here are the video details they request:

> App Demonstration Video
>Video is publicly accessible.
OAuth Consent Screen is in English.
OAuth Consent Screen shows the App Name.
URL bar of the OAuth Consent Screen fully displays the Client ID in your project which contains the project_number (This is not required for native Android and iOS apps).
Video shows the OAuth grant process that users will go through.
Video shows how the data will be used by showing functionality for each sensitive and restricted scope you've requested.
Video shows how data is accessed on each OAuth client.
You do not need to be personally visible in the demo or narrate the video. Demonstrating the process from the keyboard/screen view is fine.
If you cannot fulfill the above requirements because users are currently seeing the "Sign in disabled" screen, make sure you provide us with an email address so that we can temporarily disable the warning screen, allowing you to demonstrate all of the above video requirements.
If you cannot fulfill the above requirements because your app is an add-on that has not yet been published to the GSuite Marketplace, please reply to let us know.

**Comment by TekBear** [comment]
Yes I read about that nightmare  may take up to 6 weeks to review it is a lot of hoops to jump through. 

There is a post here https://github.com/insanum/gcalcli/issues/497#issuecomment-561215825 that gcalcli (python code base) project does a command line startup "gcalcli --client-id arg1 --client-secret arg2" then the advanced button shows up, on the OAuth screen allowing you to complete the Oauth process. For dotnet code base, on this page https://developers.google.com/calendar/quickstart/dotnet you can create a per user json file with credentials (assuming it has equivalent "arg1" and "arg2" values for dotnet code base). This would be used to override the hard coded credentials in "Gminder.exe". Would the method work for Gminder and be less work to do?

**Comment by milowg** [comment]
Sorry for the delay on this, I've been working back and forth with Google. I believe the app should now be verified, and so this issue should be fixed. @TekBear can you try it again and let me know if it works for you?

**Comment by TekBear** [comment]
Thanks @milowg it is working now, I have been testing since yesterday and had some odd problems until I turned off "test connectivity before downloading events" option. What method is the connectivity test using is it pinging a server? 

I will report back in a few days after I do a bit more testing.

**Comment by milowg** [comment]
That just does a ping of www.google.com .. strange that it does not work.

**Comment by TekBear** [comment]
@milowg ok that for the info. This is a problem created by my (Australian) ISP who told me this:
"Your service is currently layer 2 and ICMP is blocked for all but our IP ranges.
The functionality your require is more suited to business and these are residential products.
I can however offer you a layer 3 service which will remove natting and allow you to ping.
The only problem with this is the requirement to change your PPPoE credentials."

I have never encountered this before and do not completely understand the explanation. This breaks network diagnostics and legitimately ping www.google.com - nuts!

**Comment by milowg** [comment]
Sorry to hear that, not sure why ICMP (Ping) is a business need only. At least you have a way around it for GMinder!
